### ISSUE TITLE
Linthesia UI responce is too slow

### ISSUE THREAD

**Issue by suhr** [linthesia/linthesia#14]

**Comment by StefanTT** [comment]
Same happens for me on Ubuntu 16.04 on a high end machine. It is barely usable, even mouse movement takes ~ 5 seconds until the button under the mouse highlights.

I cloned the sources and compiled linthesia myself. When I disable double buffering the UI responds quick as it should. Drawback is some flickering, of course.

**Comment by RushOnline** [comment]
Disabling "sync to vblank" help me too. Thank you!

~~~bash
$ uname -a
Linux cassiopea 4.4.0-42-lowlatency #62-Ubuntu SMP PREEMPT Sat Oct 8 00:22:55 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ dkms status | grep "nvidia.*$(uname -r)" 
nvidia-340, 340.96, 4.4.0-42-lowlatency, x86_64: installed

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
~~~

**Comment by rastating** [comment]
I can confirm disabling sync to vblank in the nVidia settings on Ubuntu 16.04 also fixed this issue for me.

**Comment by mans17** [comment]
issue is ready to be closed.

**Comment by mans17** [comment]
FYI, I updated sync time from 60 to 30.
On my slow laptop, it stills"feels like a bit of lagging".
On my fast PC, it felt much faster.

You can test it there : https://github.com/mans17/linthesia/tree/master
(or even on my new branch : https://github.com/mans17/linthesia/tree/save-song-prefs )

**Comment by mk6032** [comment]
Is this expected on RPi 3B+ (armhf)? Even the initial file, output, input screen is this way. I installed with apt version 0.4.3-1+b1 from default repo.
