### ISSUE TITLE
Displaying MIDI text events

### ISSUE THREAD

**Issue by fred-wang** [linthesia/linthesia#16]
Some MIDI files contains some text (e.g. lyrics in karaoke files) which may be useful to see when playing. For example, to train playing chords one can use MIDI files with random chords and associate their names in text events. I'm not exactly sure about how the UI will look like but I have some simple change here if someone is interested: https://github.com/fred-wang/linthesia/commit/ab5d8565df9d14fccaa1da66f96931ddcb73d348

**Comment by RushOnline** [comment]
There are nothing, amigo.

**Comment by albfan** [comment]
Definitely interesting @fred-wang. Might help on #34. I found https://www.heikoplate.de/psruti.html to create midi with lyrics and this example video https://www.youtube.com/watch?v=go2xBM1FMYE

If you can recover the commit we can work on that

**Comment by fred-wang** [comment]
Hi, I think my commit was a quick hack for my own use, but here is what I have in my local copy:

```
commit 8e286a76a901d6e8ddea44dad0dca5b94d57a02e (HEAD -> print-text)
Author: Frédéric Wang <fred.wang@free.fr>
Date:   Mon Jun 20 18:50:57 2016 +0200

    Display text events in the bottom bar.

diff --git a/src/PlayingState.cpp b/src/PlayingState.cpp
index 6886a93..d6fc93b 100644
--- a/src/PlayingState.cpp
+++ b/src/PlayingState.cpp
@@ -722,6 +722,10 @@ void PlayingState::Draw(Renderer &renderer) const {
   TextWriter time_text(Layout::ScreenMarginX + 39, text_y+2, renderer, false, Layout::SmallFontSize);
   time_text << STRING(current_time << " / " << total_time << percent_complete);
 
+  for (int i = 0; i < m_state.midi->Tracks().size(); i++) {
+    time_text << " " << m_state.midi->Tracks()[i].LastText();
+  }
+
   // Draw a song progress bar along the top of the screen
   const int time_pb_width = static_cast<int>(m_state.midi->GetSongPercentageComplete() * (GetStateWidth() -
                                                                                           Layout::ScreenMarginX*2));
diff --git a/src/libmidi/MidiTrack.h b/src/libmidi/MidiTrack.h
index fa5f877..2d4002e 100644
--- a/src/libmidi/MidiTrack.h
+++ b/src/libmidi/MidiTrack.h
@@ -69,6 +69,11 @@ public:
     return m_note_set;
   }
 
+  const std::string LastText() const
+  {
+    return m_last_event == -1 ? "" : m_events[m_last_event].Text();
+  }
+
   void SetTrackId(size_t track_id);
 
   // Reports whether this track contains any Note-On MIDI events
```

**Comment by albfan** [comment]
Great, we can start from that. Any midi sample to test?

**Comment by albfan** [comment]
I found some samples and this mostly work, probably to show it better this needs to load ahead of time and color current text

**Comment by albfan** [comment]
This will not work nice on quick changes but let's put basic implementation in place
