### ISSUE TITLE
Make resource directories configurable

### ISSUE THREAD

**Issue by RushOnline** [linthesia/linthesia#20]
When developing, releasing or packaging software developer/maintainer must have flexible way to configure paths. Before merge #19 scriptdir and graphicsdir are was hardcoded to $(pkgdatadir)/graphics and $(pkgdatadir)/scripts, after merge #19 are hardcoded to ../graphics and ../scripts.

**Comment by RushOnline** [comment]
Отчасти это и мой косяк - я недоглядел и добавил в коммит #19 файл Makefile.am хотя он был чисто для локального сипользования :( Зато теперь всё будет как красиво, если примешь этот коммит! :)

**Comment by arcusfelis** [comment]
@RushOnline  Я должен чаще проверять Github. 
Спасибо за реквесты
