### ISSUE TITLE
request: Song library in linthesia

### ISSUE THREAD

**Issue by kiselev-dv** [linthesia/linthesia#27]
Hi, I'm trying to create a GameState screen with songs list. 

So user can choose a midi right inside linthesia. Later on I want to add search, categories and statistics.  But for now I'm trying to get a list of buttons for each midi in a folder, save it into shared_state, and open a TitleGameState. I'm kind of a newby in C++, I use StringTile, m.b. I'm doing that wrong, because I get only the first tile rendered correctly, all the others renders as pale rectangles.

Here is the code https://github.com/kiselev-dv/linthesia/blob/songlib/src/SongLibState.cpp

I would appreciate any guidance.

**Comment by kiselev-dv** [comment]
Looks like the problem with buttons occurs only if you call render for the same tga texture sequentially. For instance, if you alternate SongBox and OutputBox textures, problem goes away.

**Comment by mans17** [comment]
This issue is now closed.
(cf. Pull Request #28)

**Comment by albfan** [comment]
merged since 0.7.0
