### ISSUE TITLE
make more compatible with multiple monitors

### ISSUE THREAD

**Issue by jose1711** [linthesia/linthesia#33]
with two (or more) monitors of different resolution if you move linthesia from one monitor to the other one the layout is not recalculated

**Comment by mans17** [comment]
Could you be more specific about what screens are concerned with this issue ?

**Comment by jose1711** [comment]
Imagine a dual-monitor setup, both using different resolutions. On start `linthesia` resizes the window to one of the monitors if you move its window to the second monitor the size of the elements is not dynamically recalculated.

**Comment by mans17** [comment]
I mean :
- while playing ?
- while select songg
Etc....

**Comment by jose1711** [comment]
The problem concerns for instance the screen where you choose tracks to play. Linthesia is opened on a screen with resolution 1920x1080 and it properly adjusts:
![obrázok](https://user-images.githubusercontent.com/1406222/75099590-a301a880-55c3-11ea-931b-afb412e0d635.png)
then the same window is moved to a secondary screen with resolution of 1440x900:
![obrázok](https://user-images.githubusercontent.com/1406222/75099599-c0367700-55c3-11ea-8257-6478ce8be04b.png)
One would expect Linthesia notices the changed layout and trigger a recalculation of elements position.

**Comment by mans17** [comment]
I have began my fix for this screen.
Testing it tomorrow.

Please tell me if other screens required (no, in my opinion).

**Comment by jose1711** [comment]
I've tested with the latest HEAD and it works nicely now. Thank you for the fix!
