### ISSUE TITLE
Unable to run under Manjaro Linux.

### ISSUE THREAD

**Issue by Rencer** [linthesia/linthesia#35]
When try to launch Linthesia I get these errors:

(linthesia:20688): GdkGLExt-WARNING **: 22:26:17.228: cannot find PangoXSubfont

(linthesia:20688): glibmm-ERROR **: 22:26:17.228: 
unhandled exception (type std::exception) in signal handler:
what: std::exception

I tried everything that I find on the internet about this Pango-something, but none of them worked.
First I installed the program from AUR, but that gives the same error, than I compiled this, but getting again this same error.

**Comment by gekaremi** [comment]
Similar(after some attempts to find and install missing packages)
Also tried aur and now compiled myself

(linthesia:30691): GdkGLExt-WARNING **: 00:09:32.125: cannot load PangoFont

(linthesia:30691): glibmm-ERROR **: 00:09:32.147: 
unhandled exception (type std::exception) in signal handler:
what: std::exception

Trace/breakpoint trap (core dumped)

**Comment by klausrollmann** [comment]
I think this can be solved by installing the correct libpango package. There are a few, but try installing libpango-1.0.0 or libpangoft* or some other. I don't remember which one I installed, but this worked for me.

**Comment by Rencer** [comment]
> I think this can be solved by installing the correct libpango package. There are a few, but try installing libpango-1.0.0 or libpangoft* or some other. I don't remember which one I installed, but this worked for me.

No, it can't be solved, because it's MANJARO Linux (an Arch-based Linux), those packages are Debian packages. It's MANJARO LINUX, you doesn't even using Manjaro, or Arch or any Arch-based Linux, you are using somthing Debian. So your post is useless.
Oh, and next time before commenting try to understand what people already written down:
"I tried everything that I find on the internet about this Pango-something, but none of them worked."
Everything. You know what this word means?
I spent several days, (yes, really, several days!), several hours every day, to try out EVERYTHING that about this "pango"-bug, and none of them worked, because all are just about Debian-based Linuxes. It includes (because that is the VERY FIRST thing I -and definitely everybody else- do when compiling from source fails, and saw that something is missing) installing all the packages that have something to do with it.
Sorry, but I's enough! It's so utterly annoying, when guys don't read and understand what clearly is written down.You assuming that I'm the same as you, who just randomly posting in bug-reports before go and try out EVERYTHING that can be found on the internet, to solve the problem? No!
Because bug-reporting is a thing that you do AFTER YOU TRIED EVERYTHING out, to be sure, the problem you facing is really a bug or something that can not be fixed by just installing packages.

I apologies to everyone, I don't want to hurt anybody, only get pissed of a bit, when people commenting on something that they have nothing to do with it.
I'm here to seek help, to fix this Pango-bug under an Arch-based Linux, namely MANJARO Linux, I already spent lots and lots of hours to try to find a fix for this problem, nothing helped.

I think this program is abandoned, few years already passed since anything happened with it, and now it is clear that this program is written exclusively for Debian-based Linuxes. I leave this here opened in hope that someone who made this program come here and finally fix this stupid bug. Or better if they rewrite the whole thing not using Pango for their text rendering...

**Comment by mans17** [comment]
I'm using Archlinux.
Would it help you to compare my ./autogen.sh output to yours ?

**Comment by Rencer** [comment]
> I'm using Archlinux.
> Would it help you to compare my ./autogen.sh output to yours ?

And it works for you? You can compile this source?

**Comment by mans17** [comment]
Of course, I would not think it would help otherwise :-)

(I use a forked version https://github.com/mans17/linthesia but I might 
compile this main build to help you since I'm quite confident the 
differences between those forks do not interfere with your bug)




Le 2019-01-24 13:59, Rencer a écrit :

**Comment by mans17** [comment]
Since you already installed everything that pops when typing that, you obviously have those packages installed : 
```
`pacman -Qs pango
local/pango 1:1.42.4-1
    A library for layout and rendering of text
local/pangomm 2.42.0-1
    C++ bindings for Pango
local/pangox-compat 0.0.2+2+gedb9e09-3
    X Window System font support for Pango
```

then, I had quite "the same" problem you had on one of my PC and installing those fonts worked (after a reboot, donno why ^^)

```
pacman -S gconf
pacman -S ttf-bitstream-vera
pacman -S gconf-editor
pacman -S xorg-fonts-misc
pacman -S ttf-dejavu
pacman -S powerline-fonts
pacman -S fluidsynth
pacman -S artwiz-fonts
```
Nota : my "exact" error was the same as this one : https://bugs.launchpad.net/ubuntu/+source/linthesia/+bug/663962

after those commands AND a reboot, everything is fine.

**Comment by mans17** [comment]
@Rencer would you please tell us that this "issue" is now closed ?

**Comment by gekaremi** [comment]
@mans17 same, after installing and several rebootes

`(linthesia:1919): GdkGLExt-WARNING **: 21:44:48.499: cannot load PangoFont

(linthesia:1919): glibmm-ERROR **: 21:44:48.499: 
unhandled exception (type std::exception) in signal handler:
what: std::exception

Trace/breakpoint trap (core dumped)
`

Window can be opened but will crash after attempt to open midi file

`
sudo pacman -S gconf ttf-bitstream-vera   gconf-editor xorg-fonts-misc  ttf-dejavu powerline-fonts fluidsynth artwiz-fonts
warning: gconf-3.2.6+11+g07808097-4 is up to date -- reinstalling
warning: ttf-bitstream-vera-1.10-12 is up to date -- reinstalling
warning: gconf-editor-3.0.1-5 is up to date -- reinstalling
warning: xorg-fonts-misc-1.0.3-6 is up to date -- reinstalling
warning: ttf-dejavu-2.37-2 is up to date -- reinstalling
warning: powerline-fonts-2.7-2 is up to date -- reinstalling
warning: fluidsynth-1.1.11-3 is up to date -- reinstalling
warning: artwiz-fonts-1.3-10 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...
`

**Comment by mans17** [comment]
(sorry if you did that already)
- What exact build did you make ? (linthesia/linthesia:master ?)
- did you try to "make uninstall" and rebuild it from a clean new clone ?

**Comment by gekaremi** [comment]
@mans17 find out that I use `libgtkglextmm-x11-1.2.so.0` from AUR linthesia, and if delete AUR version, I cant run any linthesia
`linthesia: error while loading shared libraries: libgtkglextmm-x11-1.2.so.0: cannot open shared object file: No such file or directory`

After that I deleted AUR linthesia, but left dependence and `sudo make uninstall`
 `sudo make install`
so now is probably right build
but nothing changes

Perhaps I will surrender and install ubuntu-something :rabbit:

**Comment by mans17** [comment]
you did not get me right.
I assume you use "AUR/linthesia" (that is linthesia/linthesia in my question).

do this : 
- re-install AUR/libgtkglextmm 
    cd (whatever)lib(makepkg -si)
- remove linthesia & rebuild linthesia : 
     cd (whaterver)/linthesia/
     make uninstall
     make distclean
     ./configure --prefix=/usr/
     make
     sudo make install

**Comment by Charly6596** [comment]
I also had some problems, but mainly missing dependencies, fixed it installing the dependencies:

```cmd
yay -S gtkglextmm
yay -S gconfmm
```
Then compile it
```cmd
./autogen.sh
./configure --prefix=/usr
make
sudo make install
```
That worked for me, running Manjaro 18.0.3 Illyria

Hope it helps someone.

**Comment by Rencer** [comment]
> @mans17 find out that I use `libgtkglextmm-x11-1.2.so.0` from AUR linthesia, and if delete AUR version, I cant run any linthesia
> `linthesia: error while loading shared libraries: libgtkglextmm-x11-1.2.so.0: cannot open shared object file: No such file or directory`
> 
> After that I deleted AUR linthesia, but left dependence and `sudo make uninstall`
> `sudo make install`
> so now is probably right build
> but nothing changes
> 
> Perhaps I will surrender and install ubuntu-something rabbit

I have something that might help you...but first let me tell you why I didn't post anything here for a long time. It is not just my job and that I didn't had much time to play this trial-and-error thing with Linthesia, but there is more:
I already gave up that Linthesia will work, so I doesn't even posted anything here, because still nothing helped, and I just see the posts now doesn't even talk about THIS LINTHESIA HERE ON GITHUB, but talking about the AUR package.
I thought if you have problems with something from the AUR, you should report it at: [https://bugs.archlinux.org/index.php?project=2](url).
I never ever will understand, why people come to any forum, bug report, or anything on the internet and start mumbling about AN ENTIRELY DIFFERENT thing, or just simply can't understand what is written down, and start ASSUMING things and whatnot...
I REALLY sick of it, and nothing more on Earth that can piss me up so much, like this behaviour. 
So I don't even post. From time to time I come and look at this page, to see if there is a post that helps resolving this problem.
I will close this post and will reply to people who posts here if that is helps to fix my problem with exactly this version of Linthesia here on GitHub... I just skip everything else...

But, now back to your problem. I saw that you mentioned "libgtkglextmm-x11" and the problem.
When I first tried to install Linthesia, I didn't find that "libgtkglextmm-x11" package anywhere.
So done what I already learned, because I run into this thing many-many-many times:
When you don't find that package most of the time the reason is that the package has a different name on your Linux. You just have to "play" with the name of that package and figure out what might it be on your system. So this is how I find out in the package is named "gtkglextmm". It's there in the AUR repo.
Maybe you can try that out, and see if that fix the issue...
