### ISSUE TITLE
Snap/Flatpak/Appimage/whatever...

### ISSUE THREAD

**Issue by gekaremi** [linthesia/linthesia#36]

**Comment by LyrixCaz** [comment]
I'll also love an appimage for this

**Comment by mans17** [comment]
I made a build in my current branch.
https://github.com/mans17/linthesia/tree/save-song-prefs/releases

**Comment by mans17** [comment]
Has anywone successfully tested images ? I think only latest MIGHT work...
(although quite not confident ^^)

**Comment by gekaremi** [comment]
Hmm I tried and had this error

```
./Linthesia-2bd5cc6-x86_64.AppImage: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by ./Linthesia-2bd5cc6-x86_64.AppImage)
./Linthesia-2bd5cc6-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_LintheLuwt9q/usr/bin/../lib/libsqlite3.so.0)
./Linthesia-2bd5cc6-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/.mount_LintheLuwt9q/usr/bin/../lib/libcairo.so.2)
./Linthesia-2bd5cc6-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.30' not found (required by /tmp/.mount_LintheLuwt9q/usr/bin/../lib/libsystemd.so.0)
```

**Comment by mans17** [comment]
@gekaremi : I updated the release. The bug you showed might have disappeared.
New one has occured :-)
I'll tell you when I'm done fixing it (but you might be lucky and have it worked now !)

**Comment by gekaremi** [comment]
> @gekaremi : I updated the release. The bug you showed might have disappeared.
> New one has occured :-)
> I'll tell you when I'm done fixing it (but you might be lucky and have it worked now !)

You are absolutely right :b   

```
Linthesia detected a Gnome::Conf::Error problem and must close:

Failed to activate configuration server: The name org.gnome.GConf was not provided by any .service files


If you don't think this should have happened, please fill a bug report on : 
https://github.com/linthesia/linthesia

Thank you.
```

(kubuntu 18.10)

**Comment by cassdeckard** [comment]
I'm trying to use the current AppImage and getting that same error of "The name org.gnome.GConf was not provided by any .service files"

**Comment by albfan** [comment]
Shouldn't this be on the repo that contains Appimage sources? There's nothing we can do here for wrappers
