### ISSUE TITLE
No package 'gconfmm-3.2.6' found

### ISSUE THREAD

**Issue by JonasKress** [linthesia/linthesia#41]
Unfortunately make on Ubuntu 19.04 fails

**Comment by NathanS6677** [comment]
Same error on Debian Unstable

**Comment by NathanS6677** [comment]
Fixed by installing manually:
libgconfmm-2.6-dev
libgconfmm-2.6-1v5

**Comment by josch** [comment]
The last release of gconf was in 2013. Gconf was deprecated as part of the gnome 3 transition and is no longer maintained. Maybe you manage to compile an old gconf version on modern systems but in the long term linthesia has to be ported to its successor dconf.

**Comment by baptx** [comment]
@ghost On Lubuntu 20.04, doing `sudo apt install libgconfmm-2.6-dev libgconfmm-2.6-1v5` results in:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libgconfmm-2.6-dev
E: Unable to locate package libgconfmm-2.6-1v5
```
I also tried `sudo apt search libgconfmm`:
```
Sorting... Done
Full Text Search... Done
libgconfmm-2.6-1c2/now 2.28.3-0ubuntu2 amd64 [residual-config]
  (none)
```
And `sudo apt install libgconfmm-2.6-1c2/now`:
```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Selected version '2.28.3-0ubuntu2' ( [amd64]) for 'libgconfmm-2.6-1c2'
Selected version '2.39.93-0ubuntu1' ( [amd64]) for 'libglibmm-2.4-1c2a' because of 'libgconfmm-2.6-1c2'
Selected version '2.2.10-0.2ubuntu2' ( [amd64]) for 'libsigc++-2.0-0c2a' because of 'libglibmm-2.4-1c2a'
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgconfmm-2.6-1c2 : Depends: libglibmm-2.4-1c2a (>= 2.36.2) but it is not going to be installed
                      Depends: libsigc++-2.0-0c2a (>= 2.0.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
Any idea why it worked on Debian but not Ubuntu / Lubuntu?

**Comment by rouazana** [comment]
You can try this fork which solves the compilation issue on Ubuntu 19.04 (I tested it on 20.04): https://github.com/laf0rge/linthesia

Also this fork is a little more advanced regarding features : https://github.com/antonna987/linthesia

I can eventually provide a Dockerfile to build one or the other.

**Comment by baptx** [comment]
@rouazana thanks, I took a moment to test the fork https://github.com/laf0rge/linthesia (which is a fork of fork of a fork :D). My MIDI keyboard Akai LPK25 is recognized, the only problem is that there is no sound. I tried with QjackCtl also. With other software like amsynth, I have sound. Where you able to get sound and do you know how to fix the sound issue?
I tested without container. Usually I don't use Docker but sometimes LXC, firejail or just AppArmor.

**Comment by rouazana** [comment]
> Where you able to get sound and do you know how to fix the sound issue?

I let Linthesia play directly the sound on my MIDI device and this works fine for me.
