### ISSUE TITLE
Troubleshooting 'no text' issue

### ISSUE THREAD

**Issue by 459below** [linthesia/linthesia#42]
So I've found on one of my devices, which runs an ancient ATI Mobility Radeon HD 5470, the text isn't rendered. After some troubleshooting I've found that setting _LIBGL_ALWAYS_SOFTWARE_ fixed the problem without any noticable adverse effects.

I start it like this:
```
LIBGL_ALWAYS_SOFTWARE=1 linthesia
```

Maybe this information could go into the docs which I cannot seem to find.

**Comment by mans17** [comment]
Thank you for sharing your experience.
