### ISSUE TITLE
Can't launch the soft

### ISSUE THREAD

**Issue by felixquinton** [linthesia/linthesia#44]
I have been able to install the software without any issue.
However when I try to run it I have an error saying :
ALSA lib seq_hw.c:466:(snd_seq_hw_open) open /dev/snd/seq failed: No such file or directory
linthesia: seq.c:1178: snd_seq_client_id: Assertion 'seq' failed.
Aborted (core dumped)

**Comment by mans17** [comment]
Hi, Can you try to compile mans17/linthesia ?
We fixed several path bugs, ans this version is more verbose on crashes.

**Comment by albfan** [comment]
please reopen if you try 0.7.0 or master and still fails
