### ISSUE TITLE
Scan folders on start to load all midi files into library

### ISSUE THREAD

**Issue by mtest1** [linthesia/linthesia#48]
Linthesia used to start with open file dialog. Is there a way to load custom mid file into Linthesia at the moment?
Adding mid files to existing directories does not load them into program. Perhaps Linthesia should scan each predefined folder or have one named something like "Custom" and scan this folder for all mid files on start?

**Comment by mans17** [comment]
You should use this version that implements a midi folder (great work by kiselev).

https://github.com/mans17/linthesia

You also may be able to load << any >> midi file with command line...

**Comment by tuxutku** [comment]
how does it do it so? I've built and installed this [fork](https://github.com/rikmg/linthesia) but it doesn't accept midi files from the terminal and due to how its installed, it can't go to home directory and search there

**Comment by albfan** [comment]
solved since 0.7.0
