### ISSUE TITLE
Fix build instructions in README

### ISSUE THREAD

**Issue by fred-wang** [linthesia/linthesia#51]
I just tried https://github.com/linthesia/linthesia#compile

```
./autogen.sh
mkdir build
cd build     # Isolate compilation to speed future compilations
../configure
```

I obtain

```
configure: error: source directory already configured; run "make distclean" there first
```
Then when I run `make distclean` as suggested, the file `extra/linthesia.metainfo.xml` is deleted which makes future builds impossible.

At the end I figure out, I instead just need to skip the step `./autogen.sh` (and to restore `linthesia.metainfo.xml`) in order to build again, but I think the README should be updated.

**Comment by rikmg** [comment]
Recently the build system was updated to use meson, and the README was updated as well

**Comment by fred-wang** [comment]
@rikmg Thanks. Indeed, fixed by https://github.com/linthesia/linthesia/pull/52
