### ISSUE TITLE
No way to load additional MIDI files

### ISSUE THREAD

**Issue by ornxka** [linthesia/linthesia#61]
There is currently no way to add additional MIDI files beyond copying them to the installation directory. Per Gitter, the two options seem to be:

- add a UI button to load a MIDI file from the filesystem
- load MIDI files from ~/.local and merge them with those from the installation directory

**Comment by albfan** [comment]
I guess most versatile way would be to add a button and load on demand files.
 
 Probably add a list of recent loaded files would be helpful

**Comment by albfan** [comment]
I just checked. There's a `-f` to load directly a file

lbrary path can be modified to load files from gsettings (dconf-editor)

I recover a change from @kiselev-dv to change library-path from command-line. #62

**Comment by albfan** [comment]
I think complete #56 will help too

**Comment by albfan** [comment]
recent commits on master should help on this 8b6da69ad74c8196b37295e0efd3d60c94621624

**Comment by albfan** [comment]
I added `--lib-path` and `--reset-lib-path` to modify the music library on 5dcc91a (you can do on gsettings too)

With `-f` I think this is mostly done. Only a button for custom load through file dialog is missing

**Comment by albfan** [comment]
I played midis with -f. closing this
