### ISSUE TITLE
Notes played inaccurately in 49 key mode

### ISSUE THREAD

**Issue by jackkinsey** [linthesia/linthesia#70]
See this video:

https://user-images.githubusercontent.com/7231687/158507691-0e02bca5-200f-4e20-957b-df0c807f48f1.mp4

With the output and input device off, keyboard size set to 49 keys, and both tracks set to "play automatically," the autoplayer plays an octave up from the scrolling notes.

This also affects playing with a keyboard plugged in; I have to specifically cause e.g. C4 to be pressed on the digital keyboard, however I end up going about doing that using my MIDI keyboard, in order to play a scrolling note that's coming in at C3.

Linthesia v0.8.0.

**Comment by albfan** [comment]
Input/output setup does not make a difference. Just modify the keys puzzles linthesia.

**Comment by albfan** [comment]
fixed on d262d90
