### ISSUE TITLE
moving the song before the beginning desyncs falling notes with music

### ISSUE THREAD

**Issue by rikmg** [linthesia/linthesia#73]
if the Page Up key is used to move the song before the beginning, the falling notes and the actual music will become de-synchronized. Moving the song forward with Page Down key usually fixes the issue

**Comment by albfan** [comment]
I see the problem with page up passing the beginning of song, but can't see the problem you mention, can you add a screencast or similar? maybe the midi song is relevant too

**Comment by rikmg** [comment]
I don't think the song itself is very relevant

Here is an example with the included hannon lessons, where I press page-up at 3 seconds

https://user-images.githubusercontent.com/86574987/234524985-183946e8-3735-4269-919a-21501e743563.mp4

**Comment by albfan** [comment]
Thanks a lot, I can try that and see how this fix that

**Comment by albfan** [comment]
I just add some dead code removal and merge on 61b20ae

Thanks a lot!
