### ISSUE TITLE
Debian build files is outdated

### ISSUE THREAD

**Issue by einhander** [linthesia/linthesia#80]
Debian folder is outdated. Version states 0.4.0. Also build system settings not works for meson. `debuild -b -us -us` returns error.

Upd: here the minimal diff file to make it work again.
[minimal.diff.txt](https://github.com/linthesia/linthesia/files/11926878/minimal.diff.txt)

**Comment by albfan** [comment]
I strongly expect debian rules are not maintained here. Still your suggestions make sense so I added.

I credited you in commit cb28d43, hope name and email are correct, if possible use proper PR to provide that info
