### ISSUE TITLE
remove debian rules from repo

### ISSUE THREAD

**Issue by albfan** [linthesia/linthesia#83]
have file here to make a debian package doesn't make sense. That should be maintained elsewhere

**Comment by albfan** [comment]
Again, questions this maintainer cannot answer.

I will delete this files

**Comment by trebmuh** [comment]
I think it would be better to move the files in a specific branch rather than deleting them, as suggested above.

**Comment by albfan** [comment]
Who will mantain that branch @trebmuh? I just blindly merge changes there last time someone ask for changes to maintain debian package. Has no sense

**Comment by albfan** [comment]
removed on 839ec28

**Comment by oscaracena** [comment]
If, in the future, you need help with that (creating a Debian package), I can help. I'm used to create Debian packages, so just drop me a line. 😉

**Comment by rzr** [comment]
Yes let's coordinate on this we can do cooperative maintenance within debian game team ?

Maybe it worth to import this:

https://archive.debian.org/debian/pool/main/l/linthesia/

into:

https://salsa.debian.org/games-team/

Does this sound like a good plan ?

**Comment by oscaracena** [comment]
I can create and maintain the Debian files needed to build the package, but I am not a Debian developer myself, so I can not upload the package to any official Debian repository. If that is the goal, we need to find someone else (Cleto maybe?).

**Comment by albfan** [comment]
All this conversation should happen in a debian forum. This is just the upstream code to package
