### ISSUE TITLE
Add a description to README.md on how to output some sound

### ISSUE THREAD

**Issue by mans17** [linthesia/linthesia#86]
I guess some of us are not that familiar with MID magic.

## How to use
- In most case, just run `/usr/bin/linthesia` binary, and Enjoy :-)
- Linthesia provides you with several musics that will be installed in `/usr/share/linthesia/music/` you can use `--lib-path`  to define an other path when required. (read `linthesia -h` since last used path is preserved).
- Linthesia will use anything it finds to play sound. You might want to install `fluidsynth` or `TiMidity++` to run the midi server required for it to produce a sound. You keyboard might provide output that can (probably) be used too, if wanted.

**Comment by albfan** [comment]
PR welcome, although wiki or GitHub pages might be another solution

**Comment by mans17** [comment]
https://github.com/linthesia/linthesia/pull/87
